### ISSUE TITLE
Only live status option

### ISSUE THREAD

**Issue by fgolman** [guido-visser/vMix-M5Stick-Tally-Light#13]
I'd like to make the suggestion of an option to display only in live state, ignore safe and preview states.

This is the more traditional tally mode for on camera status.

**Comment by guido-visser** [comment]
You mean that when it's not live, just show a blank screen?

**Comment by fgolman** [comment]
Yes exactly. Live, red and LED on. Preview and safe screen and LED off.

That way, talent sees ANYTHING they know they're on.

**Comment by guido-visser** [comment]
Fair enough, I'll see if I can make this option in the Web UI :)

**Comment by Dirwinc** [comment]
I vote for this enhancement too.  

The Green/Preview color sometimes just confuses my stage talent, so it'd be nice to have a setting to treat Preview as BLACK/SAFE (rather than Green).  That way I only have to explain RED or BLACK to my stage talent.  

Explaining what "Preview" means to someone who doesn't understand vMix is not always fun (and frankly, sometimes I just don't have time!  haha :)  And the comment I've gotten a few times is "Green should mean 'Go'"!

Thanks!

**Comment by guido-visser** [comment]
Implemented this in 2.3.0 😄
