### ISSUE TITLE
Cannot find wifi 50% of the time

### ISSUE THREAD

**Issue by michaelkamerath** [guido-visser/vMix-M5Stick-Tally-Light#16]
When I make changes and reload the code back onto the stick, it cannot find the wifi 50% of the time. It's weird because it alternates being able to find the wifi, and then not. However, if I just reload the same code, it finds the wifi the next time.

**Comment by guido-visser** [comment]
I'm not sure if I can change any code that will improve this. However, will keep an eye out for it.

**Comment by guido-visser** [comment]
I added a wifi signal strength indicator the the network screen (this will be available in v2.4.0, but it's already available if you Download the ZIP of the master branch (Green Code Button > Download ZIP). I'll close this issue, since I've no idea on how to improve this by changing code. If someone has an idea, feel free to submit a PR.
