### ISSUE TITLE
Ability to set Static IP

### ISSUE THREAD

**Issue by kevev** [guido-visser/vMix-M5Stick-Tally-Light#21]
We do not use DHCP as sometimes our operators accidentally connect your main router to a customers network accidentally. If we had DHCP enabled, it would cause havoc on the customer network. We set Static IPs on all of our devices. Would it be possible to set a static IP/Netmask/Gateway/DNS ?

**Comment by kevev** [comment]
For those interested, I was able to configure a static IP by editing "e_WIFI.ino"

    // We start by connecting to a WiFi network

    // Set your Static IP address
    IPAddress local_IP(192, 168, 1, 222);
    IPAddress gateway(192, 168, 1, 1);
    IPAddress subnet(255, 255, 255, 0);
    IPAddress primaryDNS(8, 8, 8, 8); // optional
    IPAddress secondaryDNS(8, 8, 4, 4); // optional

    // Configures static IP address
    if (!WiFi.config(local_IP, gateway, subnet, primaryDNS, secondaryDNS)) {
      Serial.println("STA Failed to configure");
    }

    //WiFi.begin(&(WIFI_SSID[0]), &(WIFI_PASS[0]));
    //WiFi.softAP(ssid, password);

**Comment by guido-visser** [comment]
Thanks for the issue. I will take a look at this and see if I can make this configurable in an easy way.

**Comment by epgshare01** [comment]
Any progress on this feature? :)

**Comment by kevev** [comment]
Any progress on this feature?  :)

**Comment by guido-visser** [comment]
My plan was to work on this today, however something came up here. I hope that I can still work on this today and release v2.4.0

**Comment by guido-visser** [comment]
I'm looking into this, but it's quite a lot of work to make this possible. I hoped it was just storing 4 strings, but I'll have to store 20 integers on the memory of the stick (including optional DNS), this because splitting a string isn't really recommended. If this was Javascript I'd do it in a heartbeat, but I'm not a native C programmer and I'm still learning it 😅

Would you be okay if I added your bit of code to `e_WIFI.ino` and comment it out. If someone needs a static IP, that person can than uncomment those lines and recompile. It's not ideal, but it's a lot of effort against very little reward in my eyes.

**Comment by kevev** [comment]
Go for it!  :)

**Comment by dbussert** [comment]
> I'm looking into this, but it's quite a lot of work to make this possible. I hoped it was just storing 4 strings, but I'll have to store 20 integers on the memory of the stick (including optional DNS)

You can store an IP address as a 32 bit integer, since each part of the IP address is 8 bits. You can extract the octets with bitwise operators when you need to use them

**Comment by guido-visser** [comment]
I added the template in the new release: https://github.com/guido-visser/vMix-M5Stick-Tally-Light/releases/tag/v2.4.0

Will close this issue for now, maybe I'll pick it up in the future.
