### ISSUE TITLE
Feature request: Recording / Streaming status

### ISSUE THREAD

**Issue by ovonder** [guido-visser/vMix-M5Stick-Tally-Light#6]
Hi Guido, a nice to have would be getting the recording/streaming status.
so instead of selecting a tally id, you can also select Status.
When recording the display turns red, when streaming blue. Both,  half red, half blue.

Not sure if you can get this from 8099, perhaps you need to get if from the xml at 8088/api
kind regards Oscar

**Comment by julianlee-korea** [comment]
hi, 
Even when I record and stream on the vmix, the Tally Light works perfectly.
julian lee.

**Comment by guido-visser** [comment]
Thanks for passing the API info! Will look into it. Can't promise it will become a feature, but I like how much functionality I can fit onto the stick.

**Comment by guido-visser** [comment]
Hi Oscar,

At the moment, there is not an efficient way to get the information. It's possible, but only when I poll every second or so. I don't really want a polling mechanism, since it's a lot of overhead and drains the battery even more. I already did a [feature request on the official vMix forums](https://forums.vmix.com/posts/t24912-Expand-TCP-API-with-subscription-model-for-changes-to-XMLTEXT) to have a more efficient way of getting the information. You could +1 it and hope that the devs at vMix will pick this up. I will put this issue on hold until there's a better way of getting the information.

**Comment by guido-visser** [comment]
Good news! I got this to work with the ACTS API :) It's in v2.4.0 (https://github.com/guido-visser/vMix-M5Stick-Tally-Light/releases/tag/v2.4.0)
